### ISSUE TITLE
repo_url format not consistent between tables

### ISSUE THREAD

**Issue by Petersmit27** [JafarAkhondali/Morefixes#5]
Hello, 

Thank you for the research. I am currently checking out out the 27-03-2024 dump and tried some queries to see if I'll use this dataset over CVEfixes for my research.

I found that the PK `repo_url` for `repository` doesn't match the FK `repo_url` for `commits`.
`repo_url`s in `commits` have `.git` appended at the end compared to the ones in `repository`.

Ideally, the query
```sql
select hash
from commits,
     repository
where commits.repo_url = repository.repo_url
  and repo_language = 'Ruby'
```
Should return the hashes of all commits for a ruby project, but because of the mismatch, it gives no results.

I can use the modified query below as a workaround for now, but it's not ideal of course :)
```sql
select hash
from commits,
     repository
where commits.repo_url = concat(repository.repo_url, '.git')
  and repo_language = 'Ruby'
```

In CVEfixes, the urls end in `.git` for both tables, so it may be best to copy that for Morefixes.

**Comment by JafarAkhondali** [comment]
Dear Peter, you are correct about the bug. I'm working on a new release and will fix it on publish.
I prefer to remove the ".git" in MoreFixes for some reasons. For now, you can alter the table to remove ".git":
```SQL
UPDATE commits
SET repo_url = LEFT(repo_url, LENGTH(repo_url) - 4)
WHERE RIGHT(repo_url, 4) = '.git';
```

But if you are only interested in commit hashes, you can use:
```SQL 
select distinct hash from file_change where programming_language='Ruby'
```
I used distinct here because a commit may change multiple files. But try to use distinct regularly as for example the "repository" table contains some duplicate URLs.
For example:
```SQL

-- Duplicate repositories:
select * from (
    select repo_url, count(*) as cc from repository group by repo_url
) where cc>1
```
This is a bug and will be fixed in the next release. The main issue is that due to the large size of the dataset, I need to use the previous dumps, and it'll cause duplicates. There are many constrains I added for tables, but this was missing. Need to continue doing it.

Thanks for making the issue

**Comment by Petersmit27** [comment]
I forgot I can just update the database myself, thanks for the query

Also, I was actually testing with a bigger query, and reduced it as an example for the issue. I didn't realize the example I made could've been written differently 😅

**Comment by JafarAkhondali** [comment]
Yeah still it's bug and I should fix it, tnx for reporting

**Comment by JafarAkhondali** [comment]
@Petersmit27 This is fixed in the new version, and you can download the dump in Zenodo.
Feel free to reopen
